from agenda import Agenda
agenda = Agenda()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Adicionar()
agenda.Listar()